// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9847066e-446f-4829-9124-e3c7f0b05840";// mỗi esp sẽ có 1 tên thiết bị khác nhau 

const char SSID[]               = SECRET_SSID;
const char PASS[]               = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;

void onLed1Change();
void onLed2Change();
void onLed3Change();
void onLed4Change();
void onLed5Change();

CloudLight led1;
CloudLight led2;
CloudLight led3;
CloudLight led4;
CloudLight led5;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led1, READWRITE, ON_CHANGE, onLed1Change);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);
  ArduinoCloud.addProperty(led3, READWRITE, ON_CHANGE, onLed3Change);
  ArduinoCloud.addProperty(led4, READWRITE, ON_CHANGE, onLed4Change);
  ArduinoCloud.addProperty(led5, READWRITE, ON_CHANGE, onLed5Change);

}

// Sử dụng connection handler này để tương thích với module wifiConfig
// Nó sẽ sử dụng kết nối WiFi đã được thiết lập bởi wifiConfig.h
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);